# Generated by Django 3.2.5 on 2021-12-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='type',
            field=models.CharField(choices=[('1', 'Ответ текстом'), ('2', 'Ответ с выбором одного варианте'), ('3', 'Ответ с выбором нескольких вариантов')], max_length=50, null=True),
        ),
    ]
