# Generated by Django 3.2.5 on 2021-12-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_auto_20211228_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
