# Generated by Django 3.2.5 on 2021-12-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_poll_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
