# Generated by Django 3.2.5 on 2021-12-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_poll_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='poll',
            name='description',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
