# Generated by Django 3.2.5 on 2021-12-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_auto_20211228_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(max_length=60, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='description',
            field=models.CharField(max_length=150, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='end_date',
            field=models.DateField(null=True, verbose_name='Дата окончания опроса'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название опроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=150, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('Ответ текстом', 'Ответ текстом'), ('Ответ с выбором одного варианте', 'Ответ с выбором одного варианте'), ('Ответ с выбором нескольких вариантов', 'Ответ с выбором нескольких вариантов')], max_length=50, null=True, verbose_name='Условие'),
        ),
    ]
