# Generated by Django 3.2.5 on 2021-12-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0009_auto_20211229_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultsmodel',
            name='question',
            field=models.CharField(max_length=100),
        ),
    ]
